### ISSUE TITLE
Vue 3 - `Module '"vue-erdjs"' has no exported member 'vueErdJsStore'`

### ISSUE THREAD

**Issue by johnykes** [stephaneLeroy/vue-erdjs#10]
Hi again 😆 
I managed to install the package and update `main.ts`, but I got into a problem when trying to setup the router.

```
TS2305: Module '"vue-erdjs"' has no exported member 'vueErdJsStore'.
```

I wanted to use vueErdJsStore.logged, but it seems that is not exported. 

Somehow, the plugin it's working. I can authenticate, I refresh the page and I'm still logged in, I can logout... But I don't understand why is working and how can I check if user is logged in & how I can check the user wallet if I don't have access to `vueErdJsStore` (because is not exported). 🤔 

PS: I have `1.0.0-vue3-erdjs11-rc2` installed.

**Comment by stephaneLeroy** [comment]
Hello, you have examples in [the demo](https://github.com/stephaneLeroy/vue-erdjs/blob/vue3-migration/vue-erdjs-demo) and specifically the [transaction view](https://github.com/stephaneLeroy/vue-erdjs/blob/vue3-migration/vue-erdjs-demo/src/views/Transaction.vue).

In vue 3 version you have access ether to composition API (useVueErd()) or option API ($erd global propertie).
