### ISSUE TITLE
Web wallet sending signed transaction issue

### ISSUE THREAD

**Issue by NiftyWell** [stephaneLeroy/vue-erdjs#4]
After getting prompted to the Web Wallet & signing and sending the transaction users get redirected to the dapp with no transaction sent.
Right when user get prompted to the Web Wallet when interacting with the dapp this type error is visible in the console:
![image](https://user-images.githubusercontent.com/108471195/182648477-302f9d30-b078-4be5-839d-0cc835972c2d.png)

**Comment by NiftyWell** [comment]
Maybe due to no 
 if(this.currentStrategy instanceof WebWalletStrategy) {
    return this.currentProvider.sendTransaction(transaction);
}
in /src/providers/Providers.ts

**Comment by stephaneLeroy** [comment]
Fix in version 1.0.2-vue2-erdjs11
