### ISSUE TITLE
vue-erdjs for vue3, web wallet connection 

### ISSUE THREAD

**Issue by NiftyWell** [stephaneLeroy/vue-erdjs#6]
Hello!

I can't seem to connect using the web wallet strategy on the vue-erdjs vue3 version
I've tried connecting on the demo project available in the repository, but it doesn't work as well.
After connection, the user address and signature are present in the URL, but I get redirected to the vue-erdjs connection page as if nothing happened.

**Comment by johnykes** [comment]
Can't wait for the Vue3 compatibility guys <3

**Comment by stephaneLeroy** [comment]
> Can't wait for the Vue3 compatibility guys <3

In fact it already is ;)
You can use the version 1.0.0-vue3-erdjs11-rc2 that is compatible with Vue3 (it use composition API)

The issues opened here is related to webwallet connexion (WIP)

**Comment by stephaneLeroy** [comment]
Resolved in version 2.0.0-vue3-erdjs11-rc1
